apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: 092356264921.dkr.ecr.eu-central-1.amazonaws.com/user-service:8929a1fe6be53dcecce4e68c7ae52bf494032633
        ports:
        - containerPort: 8080